package com.xmsy.server.zxyy.webhome.modules.manager.hierarchypaychannelconfigrelationship.service.impl;

import org.springframework.stereotype.Service;
import com.baomidou.mybatisplus.service.impl.ServiceImpl;


import com.xmsy.server.zxyy.webhome.modules.manager.hierarchypaychannelconfigrelationship.dao.HierarchyPaychannelconfigRelationshipDao;
import com.xmsy.server.zxyy.webhome.modules.manager.hierarchypaychannelconfigrelationship.entity.HierarchyPaychannelconfigRelationshipEntity;
import com.xmsy.server.zxyy.webhome.modules.manager.hierarchypaychannelconfigrelationship.service.HierarchyPaychannelconfigRelationshipService;


@Service("hierarchyPaychannelconfigRelationshipService")
public class HierarchyPaychannelconfigRelationshipServiceImpl extends ServiceImpl<HierarchyPaychannelconfigRelationshipDao, HierarchyPaychannelconfigRelationshipEntity> implements HierarchyPaychannelconfigRelationshipService {


}
